# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculadora.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63\x61lculadora.proto\"6\n\x12OperacionSolicitud\x12\x0f\n\x07numero1\x18\x01 \x01(\x01\x12\x0f\n\x07numero2\x18\x02 \x01(\x01\"\'\n\x12OperacionRespuesta\x12\x11\n\tresultado\x18\x01 \x01(\x01\x32t\n\x0b\x43\x61lculadora\x12\x31\n\x05Sumar\x12\x13.OperacionSolicitud\x1a\x13.OperacionRespuesta\x12\x32\n\x06Restar\x12\x13.OperacionSolicitud\x1a\x13.OperacionRespuestab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculadora_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OPERACIONSOLICITUD']._serialized_start=21
  _globals['_OPERACIONSOLICITUD']._serialized_end=75
  _globals['_OPERACIONRESPUESTA']._serialized_start=77
  _globals['_OPERACIONRESPUESTA']._serialized_end=116
  _globals['_CALCULADORA']._serialized_start=118
  _globals['_CALCULADORA']._serialized_end=234
# @@protoc_insertion_point(module_scope)
